learning_templates_20240902/basic_app/urls.py
from django.urls import path
from basic_app import views


# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/',views.other, name='other')
]

learning_templates_20240902/learning_templates_20240902/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index, name='index'),
    path("admin/", admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

learning_templates_20240902/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates_20240902/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(requerst):
    context_dict = {'text':'hello world','number':100}
    return render(requerst, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates_20240902/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
{#        Anything outside of this will be inherited if you extend#}
        {% endblock %}
    </div>

</body>
</html>

learning_templates_20240902/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% load my_filters %}
    {% block body_block %}
        <h1>WELCOME TO INDEX</h1>
{#        <h2>This is index.html page showing!</h2>#}
        <h1>{{ text|my_cut:'hello' }}</h1>
        <h1>{{ number|add:'99' }}</h1>
    {% endblock %}

learning_templates_20240902/templates/basic_app/other.html
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <h1>Welcome to Other!</h1>
        <h2>This is an example of template inheritance</h2>
    {% endblock %}

learning_templates_20240902/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
</body>
</html>